server:
  port: 9296

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/skycai803/config-server
#          first time should be clone-on-start: true
          clone-on-start: false